version: "3.7"
services:
    backend_dev:
        build:
            context: .
            dockerfile: Dockerfile_dev
        ports:
            - 3003:3001
        environment:
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
            WALLET: "/app/oracle/wallet"
        volumes:
            - ".:/app"
            - "/app/node_modules"
            - "/app/backup"
            - "./oracle:/opt/oracle/instantclient_19_10/network"
        entrypoint : [ "npm","run", "start:nodemon" ]
        container_name: reddit_ts_backend_dev
        image: reddit_ts_backend:dev
    #redis:
    #    restart: always
    #    container_name: reddit_redis2
    #    image: redis:alpine
    #    ports:
    #        - "6381:6379"
    #    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
networks:
    default:
        name: composite_network
        external : true
        