version: "3.7"
services:
    backend_prod:
        build:
            context: .
            dockerfile: Dockerfile_prod
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: "production"
            LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_10"
            WALLET: "/app/oracle/wallet"
        volumes:
            - "/app/node_modules"
            #- ".:/app"
        container_name: reddit_ts_backend_prod
        image: reddit_ts_backend:prod
        #networks:
        #    default:
        #        ipv4_address: 172.19.0.3
        entrypoint: [ "npm", "run", "start:nodemon" ]
        #restart: always
    redis:
        restart: always
        container_name: reddit_redis2
        image: redis:alpine
        ports:
            - "6381:6379"
        #command: [ sh, -c, "rm -f /data/dump.rdb && redis-server" ]
    nltk:
        restart: always
        build: ./nltk_v2
        ports:
            - "5005:5005"
        expose:
            - 5005
        container_name: nltk_prod
        command: pm2-runtime start main.py
        image: nltk:prod
        deploy:
            resources:
                limits:
                    cpus: '0.8'
                    memory: 6000M

networks:
    default:
        name: composite_network
        external: true
