FROM node:19-buster
WORKDIR /app


RUN apt update && apt install -y libaio1 libaio-dev
ADD https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip /opt/oracle/instantclient.zip
RUN unzip /opt/oracle/instantclient.zip -d /opt/oracle
RUN echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig
COPY ./oracle/admin /opt/oracle/instantclient_19_10/network/admin

COPY package*.json ./
RUN apt install libsdl-pango-dev -y
RUN npm install
#RUN npm i -g typescript ts-node
COPY . ./

EXPOSE 3000
#CMD [ "npm","run", "start:prod" ]
