version: "3.7"
services:
    worker-insert:
        build:
            context: .
        volumes:
            - ".:/app"
            - "/app/node_modules"
        image: worker:dev
        command: npm run start:insertFail
        container_name: worker-insert