version: "3.7"
services:
    worker-test:
        build:
            context: .
        volumes:
            - ".:/app"
            - "/app/node_modules"
        image: worker:dev
        command: nodemon --exec npm run test
        container_name: worker-test